### ISSUE TITLE
Cope with a lot of warnings in history loading

### ISSUE THREAD

**Issue by sserov** [Alexander-Serov/tinkoff_analysis#9]

**Comment by sserov** [comment]
Found that the problem comes from the dirty data got from the server. Some days contain more than one record but some do not contain any. (Also #7)
![изображение](https://user-images.githubusercontent.com/22429359/113461988-8a4efd80-9427-11eb-9d53-37650cd0f5c8.png)

**Comment by Alexander-Serov** [comment]
Так как там все вместе в этом пр и нет тестов, трудно понять, разрешена ли эта проблема. Ну, думаю, мы вернемся к этой ишшу если что.
